Repository getsentry/sentry-symfony, pull requests merged in 2020-11, with the labels that each got.

#373 Make command lazily loaded
  CHANGELOG.md
  src/Command/SentryTestCommand.php
Labels: Status: Confirmed, Type: Improvement

#385 Update the dependencies and require the SDK 3.x
  .github/workflows/tests.yaml
  CHANGELOG.md
  README.md
  UPGRADE-4.0.md
  composer.json
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/EventListener/MessengerListener.php
  src/EventListener/RequestListener.php
  test/BaseTestCase.php
  test/Command/SentryTestCommandTest.php
  test/DependencyInjection/ConfigurationTest.php
  test/DependencyInjection/SentryExtensionTest.php
  test/End2End/End2EndTest.php
  test/End2End/StubTransportFactory.php
  test/EventListener/ConsoleListenerTest.php
  test/EventListener/MessengerListenerTest.php
  test/EventListener/RequestListenerTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Feature

#389 Support PHPUnit 9
  .github/workflows/tests.yaml
  composer.json
  test/BaseTestCase.php
  test/DependencyInjection/ConfigurationTest.php
Labels: Status: Confirmed, Type: Improvement

#387 Use the hub injected in the constructor of the listeners rather than retrieving it from the SDK singleton
  CHANGELOG.md
  UPGRADE-4.0.md
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/EventListener/ConsoleCommandListener.php
  src/EventListener/ConsoleListener.php
  src/EventListener/ErrorListener.php
  src/EventListener/MessengerListener.php
  src/EventListener/RequestListener.php
  src/EventListener/SubRequestListener.php
  src/Resources/config/services.xml
  src/SentryBundle.php
  test/BaseTestCase.php
  test/DependencyInjection/ConfigurationTest.php
  test/DependencyInjection/SentryExtensionTest.php
  test/EventListener/ConsoleCommandListenerTest.php
  test/EventListener/ConsoleListenerTest.php
  test/EventListener/ErrorListenerTest.php
  test/EventListener/MessengerListenerTest.php
  test/EventListener/RequestListenerTest.php
  test/EventListener/SubRequestListenerTest.php
  test/SentryBundleTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#392 Use symfony kernel
  phpstan-baseline.neon
  src/EventListener/ErrorListener.php
Labels: Status: Confirmed, Type: Bug
