Repository getsentry/sentry-symfony, pull requests merged in 2020-12, with the labels that each got.

#400 Fix build
  .github/workflows/tests.yaml
  composer.json
  phpstan-baseline.neon
  phpunit.xml
  src/EventListener/ErrorListener.php
  src/EventListener/RequestListener.php
  src/EventListener/SubRequestListener.php
  src/aliases.php
Labels: Status: Confirmed

#399 Allow PHP 8
  .github/workflows/tests.yaml
  CHANGELOG.md
  composer.json
Labels: Status: Confirmed, Type: Improvement

#398 Fix: Remove version constraint
  README.md
Labels: Status: Confirmed, Type: Documentation

#403 Move the static analysis and CS jobs to a separate GitHub Actions workflow
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
  composer.json
Labels: Status: Confirmed, Type: Improvement
