Repository getsentry/sentry-symfony, pull requests merged in 2021-04, with the labels that each got.

#467 Add global switch to allow disabling all instrumentations for the tracing feature
  phpstan-baseline.neon
  src/DependencyInjection/Compiler/DbalTracingPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  tests/DependencyInjection/Compiler/DbalTracingPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/tracing_disabled.php
  tests/DependencyInjection/Fixtures/xml/tracing_disabled.xml
  tests/DependencyInjection/Fixtures/yml/tracing_disabled.yml
  tests/DependencyInjection/SentryExtensionTest.php
  var/log/.gitignore
Labels: Status: Confirmed, Type: Improvement

#478 Fix missing `sentry.tracing.enabled` service container parameter
  src/DependencyInjection/SentryExtension.php
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Bug

#480 Force installing the same version for all Symfony components during the CI
  .github/workflows/tests.yaml
  CHANGELOG.md
  composer.json
Labels: Status: Confirmed, Type: Improvement

#477 Add distributed tracing support for the Symfony Cache component
  .github/workflows/tests.yaml
  CHANGELOG.md
  composer.json
  psalm-baseline.xml
  src/DependencyInjection/Compiler/CacheTracingPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  src/SentryBundle.php
  src/Tracing/Cache/TraceableCacheAdapter.php
  src/Tracing/Cache/TraceableCacheAdapterTrait.php
  src/Tracing/Cache/TraceableTagAwareCacheAdapter.php
  tests/DependencyInjection/Compiler/CacheTracingPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/full.yml
Labels: Status: Confirmed, Type: Feature

#465 Improve symfony response times when tracing is enabled
  src/EventListener/TracingRequestListener.php
  src/Resources/config/services.xml
  tests/EventListener/TracingRequestListenerTest.php
Labels: Status: Confirmed, Type: Bug

#352 Add full command to extras
  CHANGELOG.md
  src/EventListener/ConsoleListener.php
  tests/End2End/App/Command/MainCommand.php
  tests/End2End/App/config.yml
  tests/End2End/End2EndTest.php
  tests/End2End/StubTransportFactory.php
  tests/EventListener/AbstractConsoleListenerTest.php
Labels: Status: Confirmed, Type: Improvement

#487 Fix the conditions to automatically enable the tracing of the cache adapters
  .github/workflows/tests.yaml
  CHANGELOG.md
  composer.json
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  tests/DependencyInjection/Compiler/CacheTracingPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: Status: Confirmed, Type: Bug

#486 Add missing tests for the traceable cache adapters
  .github/workflows/tests.yaml
  phpstan-baseline.neon
  src/Tracing/Cache/TraceableCacheAdapterTrait.php
  tests/Tracing/Cache/AbstractTraceableCacheAdapterTest.php
  tests/Tracing/Cache/TraceableCacheAdapterTest.php
  tests/Tracing/Cache/TraceableTagAwareCacheAdapterTest.php
Labels: Status: Confirmed, Type: Improvement

#489 Fix deprecations triggered by Symfony 5.3
  CHANGELOG.md
  phpstan-baseline.neon
  src/EventListener/AbstractTracingRequestListener.php
  src/EventListener/KernelEventForwardCompatibilityTrait.php
  src/EventListener/RequestListener.php
  src/EventListener/SubRequestListener.php
  src/EventListener/TracingRequestListener.php
  src/EventListener/TracingSubRequestListener.php
  tests/EventListener/RequestListenerTest.php
  tests/EventListener/SubRequestListenerTest.php
Labels: Status: Confirmed, Type: Improvement

#490 Fix deprecations triggered by Symfony 5.3
  CHANGELOG.md
  phpstan-baseline.neon
  src/EventListener/KernelEventForwardCompatibilityTrait.php
  src/EventListener/RequestListener.php
  src/EventListener/SubRequestListener.php
  test/EventListener/RequestListenerTest.php
Labels: Status: Confirmed, Type: Improvement
