Repository getsentry/sentry-symfony, pull requests merged in 2021-02, with the labels that each got.

#429 Rename the ConsoleCommandListener class to ConsoleListener
  CHANGELOG.md
  phpstan-baseline.neon
  phpunit.xml
  psalm-baseline.xml
  psalm.xml
  src/EventListener/ConsoleCommandListener.php
  src/EventListener/ConsoleListener.php
  src/Resources/config/services.xml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/End2End/End2EndTest.php
  tests/EventListener/AbstractConsoleListenerTest.php
  tests/EventListener/ConsoleCommandListenerTest.php
  tests/EventListener/ConsoleListenerTest.php
Labels: Status: Confirmed, Type: Deprecation

#434 Add kernel.project_dir as default prefix
  CHANGELOG.md
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/End2End/End2EndTest.php
Labels: Status: Confirmed, Type: Bug

#444 Remove outdated instructions to integrate the bundle with Monolog
  README.md
Labels: Status: Confirmed, Type: Documentation

#445 Add a warning about the installation error that can happen if the SensioFrameworkExtra bundle is installed
  README.md
Labels: Status: Confirmed, Type: Documentation

#426 Add doctrine dbal tracing support that is optional to enable
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
  CHANGELOG.md
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  src/DependencyInjection/Compiler/DbalTracingPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  src/SentryBundle.php
  src/Tracing/Doctrine/DBAL/Compatibility/DriverInterface.php
  src/Tracing/Doctrine/DBAL/Compatibility/ExceptionConverterDriverInterface.php
  src/Tracing/Doctrine/DBAL/Compatibility/MiddlewareInterface.php
  src/Tracing/Doctrine/DBAL/ConnectionConfigurator.php
  src/Tracing/Doctrine/DBAL/TracingDriver.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
  src/Tracing/Doctrine/DBAL/TracingDriverMiddleware.php
  src/aliases.php
  tests/DependencyInjection/Compiler/DbalTracingPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/dbal_tracing_enabled.php
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/dbal_tracing_enabled.xml
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/dbal_tracing_enabled.yml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/DoctrineTestCase.php
  tests/Tracing/Doctrine/DBAL/TracingDriverConnectionTest.php
  tests/Tracing/Doctrine/DBAL/TracingDriverMiddlewareTest.php
  tests/Tracing/Doctrine/DBAL/TracingDriverTest.php
Labels: Status: Confirmed, Type: Feature

#448 fix before_breadcrumb example in upgrade-4.0 doc
  UPGRADE-4.0.md
Labels: Status: Confirmed, Type: Documentation

#447 Add a GitHub Actions workflow to trigger the release of a new version
  .github/workflows/publish-release.yaml
Labels: Status: Confirmed

#430 Implementation of optional sentry tracing with twig
  .github/workflows/tests.yaml
  CHANGELOG.md
  Makefile
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  psalm.xml
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  src/Tracing/Twig/TwigTracingExtension.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/php/twig_tracing_enabled.php
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/xml/twig_tracing_enabled.xml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/Fixtures/yml/twig_tracing_enabled.yml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/Stubs/Profile.phpstub
  tests/Tracing/Twig/TwigTracingExtensionTest.php
Labels: Status: Confirmed, Type: Feature

#451 Fix Codecov warning due to too low fetch depth
  .craft.yml
  .editorconfig
  .github/workflows/publish-release.yaml
  .github/workflows/tests.yaml
Labels: Status: Confirmed, Type: Improvement

#452 Improve the install instructions in the README
  README.md
Labels: Status: Confirmed, Type: Documentation
