Repository getsentry/sentry-symfony, pull requests merged in 2021-03, with the labels that each got.

#455 Run the CI on develop branch
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
Labels: Status: Confirmed

#423 Initial implementation of sentry tracing with tests
  CHANGELOG.md
  composer.json
  phpstan-baseline.neon
  phpunit.xml
  src/DependencyInjection/SentryExtension.php
  src/EventListener/AbstractTracingRequestListener.php
  src/EventListener/TracingRequestListener.php
  src/EventListener/TracingSubRequestListener.php
  src/Resources/config/services.xml
  src/aliases.php
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/EventListener/TracingRequestListenerTest.php
  tests/EventListener/TracingSubRequestListenerTest.php
  tests/bootstrap.php
Labels: Status: Confirmed, Type: Feature

#454 Fix empty or null DSN not disabling Sentry
  CHANGELOG.md
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/Fixtures/php/empty_dsn.php
  tests/DependencyInjection/Fixtures/xml/empty_dsn.xml
  tests/DependencyInjection/Fixtures/yml/empty_dsn.yml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Bug

#457 Allow explicit null value for dsn configuration option
  CHANGELOG.md
  src/DependencyInjection/SentryExtension.php
  tests/DependencyInjection/Fixtures/php/dsn_empty_string.php
  tests/DependencyInjection/Fixtures/php/dsn_false.php
  tests/DependencyInjection/Fixtures/php/dsn_null.php
  tests/DependencyInjection/Fixtures/xml/dsn_empty_string.xml
  tests/DependencyInjection/Fixtures/xml/dsn_false.xml
  tests/DependencyInjection/Fixtures/xml/dsn_null.xml
  tests/DependencyInjection/Fixtures/yml/dsn_empty_string.yml
  tests/DependencyInjection/Fixtures/yml/dsn_false.yml
  tests/DependencyInjection/Fixtures/yml/dsn_null.yml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Bug

#461 Fix failing unit tests after Symfony issue #38019 bugfix
  composer.json
  tests/EventListener/TracingRequestListenerTest.php
Labels: Status: Confirmed, Type: Improvement

#460 Add support for distributed tracing when running a console command
  CHANGELOG.md
  src/EventListener/TracingConsoleListener.php
  src/Resources/config/services.xml
  tests/EventListener/TracingConsoleListenerTest.php
Labels: Status: Confirmed, Type: Feature

#472 Intercept failures in the RequestFetcher
  CHANGELOG.md
  src/Integration/RequestFetcher.php
  tests/Integration/RequestFetcherTest.php
Labels: Status: Confirmed, Type: Bug
