Repository getsentry/sentry-symfony, pull requests merged in 2021-05, with the labels that each got.

#495 Fix fatal error when the `SERVER_PROTOCOL` header is missing
  CHANGELOG.md
  phpstan-baseline.neon
  src/EventListener/TracingRequestListener.php
  tests/EventListener/TracingRequestListenerTest.php
Labels: Status: Confirmed, Type: Bug

#501 Fix CacheItem detection
  CHANGELOG.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: Status: Confirmed, Type: Bug

#504 Make the transport factory configurable in the bundle's config
  CHANGELOG.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Feature

#510 Add the `sentry_trace_meta()` Twig function to print the `sentry-trace` HTML meta tag
  CHANGELOG.md
  src/Resources/config/services.xml
  src/Twig/SentryExtension.php
  tests/Twig/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Feature

#513 Fix: Use json instead of yaml for a fenced code block
  README.md
Labels: Type: Documentation, Type: Improvement

#514 Fix: Add missing vendor name
  README.md
Labels: Type: Documentation, Type: Improvement

#506 Cache contracts is a required dependency (not a dev-dependency)
  composer.json
Labels: Status: Confirmed, Type: Bug

#515 Make the list of commands for which distributed tracing is active configurable
  CHANGELOG.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/EventListener/TracingConsoleListener.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/console_tracing_enabled.php
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/console_tracing_enabled.xml
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/console_tracing_enabled.yml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/EventListener/TracingConsoleListenerTest.php
Labels: Status: Confirmed, Type: Feature
