Repository getsentry/sentry-symfony, pull requests merged in 2021-01, with the labels that each got.

#361 Make the RequestIntegration integration fetch the request from the request stack
  .github/workflows/tests.yaml
  CHANGELOG.md
  composer.json
  src/DependencyInjection/SentryExtension.php
  src/Integration/RequestFetcher.php
  src/Resources/config/services.xml
  test/DependencyInjection/Fixtures/php/ignore_errors_integration_overridden.php
  test/DependencyInjection/Fixtures/xml/ignore_errors_integration_overridden.xml
  test/DependencyInjection/Fixtures/yml/ignore_errors_integration_overridden.yml
  test/DependencyInjection/SentryExtensionTest.php
  test/Integration/RequestFetcherTest.php
Labels: Status: Confirmed, Type: Improvement

#406 Remove the config section related to Monolog
  CHANGELOG.md
  UPGRADE-4.0.md
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/monolog_handler.php
  tests/DependencyInjection/Fixtures/php/monolog_handler_disabled.php
  tests/DependencyInjection/Fixtures/xml/monolog_handler.xml
  tests/DependencyInjection/Fixtures/xml/monolog_handler_disabled.xml
  tests/DependencyInjection/Fixtures/yml/monolog_handler.yml
  tests/DependencyInjection/Fixtures/yml/monolog_handler_disabled.yml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#407 Remove the listener priorities configuration options
  .github/workflows/tests.yaml
  CHANGELOG.md
  UPGRADE-4.0.md
  composer.json
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/EventListener/RequestListener.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/console_command_listener_overridden_priority.php
  tests/DependencyInjection/Fixtures/php/error_listener_overridden_priority.php
  tests/DependencyInjection/Fixtures/php/messenger_listener_overridden_priority.php
  tests/DependencyInjection/Fixtures/php/request_listener_overridden_priority.php
  tests/DependencyInjection/Fixtures/php/sub_request_listener_overridden_priority.php
  tests/DependencyInjection/Fixtures/xml/console_command_listener_overridden_priority.xml
  tests/DependencyInjection/Fixtures/xml/error_listener_overridden_priority.xml
  tests/DependencyInjection/Fixtures/xml/messenger_listener_overridden_priority.xml
  tests/DependencyInjection/Fixtures/xml/request_listener_overridden_priority.xml
  tests/DependencyInjection/Fixtures/xml/sub_request_listener_overridden_priority.xml
  tests/DependencyInjection/Fixtures/yml/console_command_listener_overridden_priority.yml
  tests/DependencyInjection/Fixtures/yml/error_listener_overridden_priority.yml
  tests/DependencyInjection/Fixtures/yml/messenger_listener_overridden_priority.yml
  tests/DependencyInjection/Fixtures/yml/request_listener_overridden_priority.yml
  tests/DependencyInjection/Fixtures/yml/sub_request_listener_overridden_priority.yml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/EventListener/RequestListenerTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#408 Add Psalm
  .github/workflows/static-analysis.yaml
  Makefile
  composer.json
  psalm.xml
  src/DependencyInjection/SentryExtension.php
  src/EventListener/ErrorListener.php
  src/aliases.php
Labels: Status: Confirmed, Type: Improvement

#409 Prefer usage of the existing HttpMessageFactoryInterface service for the RequestFetcher class
  CHANGELOG.md
  src/Integration/RequestFetcher.php
  src/Resources/config/services.xml
Labels: Status: Confirmed, Type: Improvement

#412 Fix version fetch
  src/Transport/TransportFactory.php
Labels: Status: Confirmed, Type: Bug

#411 Allow pretty version 2
  composer.json
Labels: Status: Confirmed, Type: Improvement

#413 Fix UPGRADE file
  UPGRADE-4.0.md
Labels: Status: Confirmed, Type: Documentation

#414 Change the priorities of the RequestListener and SubRequestListener listeners
  CHANGELOG.md
  UPGRADE-4.0.md
  src/Resources/config/services.xml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Breaking, Type: Improvement

#415 Add a warning on top of UPGRADE doc for SDK 3.0
  UPGRADE-4.0.md
Labels: Type: Documentation, Type: Improvement

#416 sentry.options.integrations expects the name of the service without the @ prefix
  UPGRADE-4.0.md
Labels: Status: Confirmed, Type: Documentation

#417 Added missing schema option
  CHANGELOG.md
  src/Resources/config/schema/sentry-1.0.xsd
Labels: Status: Confirmed, Type: Bug

#420 Test messenger configuration
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Improvement

#425 Fix regression that send PII even when the send_default_pii option is off
  CHANGELOG.md
  phpstan-baseline.neon
  src/EventListener/RequestListener.php
  tests/EventListener/RequestListenerTest.php
Labels: Status: Confirmed, Type: Bug

#428 Fix capture of console errors when the register_error_listener option is disabled
  CHANGELOG.md
  src/DependencyInjection/SentryExtension.php
  src/EventListener/ConsoleCommandListener.php
  tests/DependencyInjection/SentryExtensionTest.php
  tests/EventListener/ConsoleCommandListenerTest.php
Labels: Status: Confirmed, Type: Bug
