Repository getsentry/sentry-symfony, pull requests merged in 2022-10, with the labels that each got.

#657 test: Add dsn to e2e test config
  phpstan.neon
  tests/End2End/App/config.yml
Labels: Type: Improvement, Status: Confirmed

#656 Fix Symfony 6 deprecations in E2E test
  tests/End2End/App/Kernel.php
  tests/End2End/App/deprecations_for_6.yml
Labels: Type: Deprecation

#655 fix: Update span ops
  src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
Labels: Type: Bug, Status: In Progress

#658 docs: Update changelog
  CHANGELOG.md
Labels: Type: Documentation

#659 Prepare release 4.3.1
  CHANGELOG.md
Labels: Type: Documentation

#660 Merge branch 'master' into develop
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  phpstan.neon
  src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
  tests/End2End/App/Kernel.php
  tests/End2End/App/config.yml
  tests/End2End/App/deprecations_for_6.yml
Labels: Status: Confirmed

#662 ref: Use constant for the SDK version
  .craft.yml
  CHANGELOG.md
  scripts/bump-version.sh
  src/DependencyInjection/SentryExtension.php
  src/SentryBundle.php
  src/Transport/TransportFactory.php
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Type: Improvement, Status: Confirmed

#661 feat: Add support for Dynamic Sampling
  CHANGELOG.md
  composer.json
  src/EventListener/TracingConsoleListener.php
  src/EventListener/TracingRequestListener.php
  src/Twig/SentryExtension.php
  tests/EventListener/TracingConsoleListenerTest.php
  tests/EventListener/TracingRequestListenerTest.php
  tests/Tracing/HttpClient/TraceableHttpClientTest.php
  tests/Twig/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Feature

#665 feat: Add support for Dynamic Sampling
  CHANGELOG.md
  composer.json
  src/EventListener/TracingConsoleListener.php
  src/EventListener/TracingRequestListener.php
  src/Twig/SentryExtension.php
  tests/EventListener/TracingConsoleListenerTest.php
  tests/EventListener/TracingRequestListenerTest.php
  tests/Twig/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Feature
