Repository getsentry/sentry-symfony, pull requests merged in 2022-02, with the labels that each got.

#578 Update PHPStan and PHP-CS-Fixer to their latest version
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  src/DependencyInjection/SentryExtension.php
  src/EventListener/RequestListener.php
  src/EventListener/TracingRequestListener.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnectionFactoryInterface.php
  src/Tracing/Doctrine/DBAL/TracingDriverForV3.php
  tests/DependencyInjection/SentryExtensionTest.php
  tests/EventListener/AbstractConsoleListenerTest.php
  tests/EventListener/MessengerListenerTest.php
  tests/EventListener/RequestListenerTest.php
  tests/Tracing/Cache/AbstractTraceableCacheAdapterTest.php
  tests/Tracing/Cache/TraceableTagAwareCacheAdapterTest.php
  tests/Tracing/Doctrine/DBAL/TracingDriverConnectionTest.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV2Test.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV3Test.php
  tests/Tracing/Twig/TwigTracingExtensionTest.php
Labels: Type: Improvement, Status: Confirmed

#586 Fix deprecation: PDOStatement::bindParam(): Passing null to $maxLength
  CHANGELOG.md
  phpstan-baseline.neon
  src/Tracing/Doctrine/DBAL/TracingStatementForV2.php
  src/Tracing/Doctrine/DBAL/TracingStatementForV3.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV2Test.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV3Test.php
Labels: Type: Improvement, Status: Confirmed

#597 Add support for accessing dbal native connection
  CHANGELOG.md
  phpstan-baseline.neon
  src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnectionInterface.php
  src/Tracing/Doctrine/DBAL/TracingServerInfoAwareDriverConnection.php
  tests/Tracing/Doctrine/DBAL/Fixture/NativeDriverConnectionInterfaceStub.php
  tests/Tracing/Doctrine/DBAL/Fixture/ServerInfoAwareConnectionStub.php
  tests/Tracing/Doctrine/DBAL/TracingDriverConnectionFactoryTest.php
  tests/Tracing/Doctrine/DBAL/TracingDriverConnectionTest.php
  tests/Tracing/Doctrine/DBAL/TracingServerInfoAwareDriverConnectionTest.php
Labels: Status: Confirmed, Type: Feature

#604 Add Sentry Logo to readme
  README.md
Labels: Status: Confirmed, Type: Documentation
