Repository getsentry/sentry-symfony, pull requests merged in 2022-05, with the labels that each got.

#613 Default Statement::bindParam $length to 0, as using null causes a deprecation with PHP8+
  CHANGELOG.md
  phpstan-baseline.neon
  src/Tracing/Doctrine/DBAL/TracingStatementForV2.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV2Test.php
Labels: Type: Bug, Status: Confirmed

#628 fix: Make getTraceMeta() function public.
  CHANGELOG.md
  src/Twig/SentryExtension.php
Labels: Type: Bug, Status: Confirmed

#635 SentryTestCommand > Fix deprecated `$defaultName`
  CHANGELOG.md
  src/Command/SentryTestCommand.php
  src/Resources/config/services.xml
  tests/Command/SentryTestCommandTest.php
Labels: Type: Improvement

#634 Require at least the version `3.5` of the core Sentry SDK
  .github/workflows/tests.yaml
  composer.json
  tests/End2End/App/config.yml
  tests/End2End/End2EndTest.php
Labels: Type: Improvement, Status: Confirmed

#593 Support http_connect_timeout and http_timeout options
  CHANGELOG.md
  src/DependencyInjection/Configuration.php
  src/Resources/config/schema/sentry-1.0.xsd
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Status: Confirmed, Type: Feature
