Repository getsentry/sentry-symfony, pull requests merged in 2023-10, with the labels that each got.

#769 Fix broken build and update PHPStan baseline
  phpstan-baseline.neon
  tests/EventListener/MessengerListenerTest.php
Labels: Type: Improvement

#770 Drop the `phpspec/prophecy` dev dependency
  composer.json
  src/Command/SentryTestCommand.php
  src/Resources/config/services.xml
  tests/BaseTestCase.php
  tests/Command/SentryTestCommandTest.php
Labels: Type: Improvement

#772 Harden GitHub Workflows permissions
  .github/workflows/publish-release.yaml
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
Labels: Type: Improvement

#773 Update GitHub Actions
  .github/workflows/publish-release.yaml
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
Labels: Type: Improvement

#767 Add jobs for PHP `8.3` to the CI
  .github/workflows/static-analysis.yaml
  .github/workflows/tests.yaml
Labels: Type: Improvement

#750 Add support for `symfony/psr-http-message-bridge: ^6.4`
  composer.json
Labels: Type: Bug

#775 Prepare 4.12.0
  CHANGELOG.md
Labels: Type: Documentation
