Repository getsentry/sentry-symfony, pull requests merged in 2023-04, with the labels that each got.

#712 fix(tests): Pin symfony/http-client to ﻿<5.4.22 || <6.2.8
  .github/workflows/tests.yaml
  composer.json
Labels: Type: Bug

#711 Drop kernel.build_dir param below Symfony 5.2
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: Type: Bug, Status: In Progress

#715 Revert "fix(tests): Pin symfony/http-client to ﻿<5.4.22 || <6.2.8 (#7…
  .github/workflows/tests.yaml
  composer.json
Labels: Type: Improvement, Status: Backlog
