Repository getsentry/sentry-symfony, pull requests merged in 2023-06, with the labels that each got.

#725 Bump base SDK
  composer.json
Labels: Type: Improvement

#729 Prepare 4.9.0
  CHANGELOG.md
Labels: Type: Documentation

#731 Make TracingDriverForV32 implements VersionAwarePlatformDriver to handle platform version
  src/Tracing/Doctrine/DBAL/TracingDriverForV32.php
  tests/Tracing/Doctrine/DBAL/TracingDriverForV32Test.php
Labels: Type: Bug

#733 Prepare 4.9.1
  CHANGELOG.md
Labels: Type: Documentation

#736 Revert dbal changes
  .github/workflows/tests.yaml
  CHANGELOG.md
  psalm-baseline.xml
  src/Tracing/Doctrine/DBAL/TracingDriverForV32.php
  src/aliases.php
  tests/DoctrineTestCase.php
  tests/Tracing/Doctrine/DBAL/TracingDriverForV32Test.php
  tests/Tracing/Doctrine/DBAL/TracingDriverForV3Test.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV3Test.php
Labels: Type: Bug, Status: In Progress

#741 Remove `dev-master` branch alias
  composer.json
Labels: Type: Improvement, Status: In Progress
