Repository getsentry/sentry-symfony, pull requests merged in 2023-12, with the labels that each got.

#785 Remove monolog dependency
  composer.json
Labels: Type: Improvement

#786 Fix the decoration of the HTTP client when tracing is enabled
  src/DependencyInjection/Compiler/HttpClientTracingPass.php
  tests/DependencyInjection/Compiler/HttpClientTracingPassTest.php
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Type: Bug

#761 Symfony 7 support
  .github/workflows/tests.yaml
  .php-cs-fixer.dist.php
  composer.json
  phpstan-baseline.neon
  src/EventListener/MessengerListener.php
  src/Tracing/HttpClient/AbstractTraceableHttpClient.php
  tests/End2End/App/Messenger/FooMessageHandler.php
  tests/End2End/App/messenger.yml
  tests/End2End/End2EndTest.php
  tests/EventListener/ErrorListenerTest.php
  tests/EventListener/LoginListenerTest.php
  tests/EventListener/RequestListenerTest.php
  tests/EventListener/SubRequestListenerTest.php
  tests/EventListener/TracingRequestListenerTest.php
  tests/EventListener/TracingSubRequestListenerTest.php
Labels: Type: Improvement, Type: Discussion

#792 Fix the HTTP client decoration when no `http_client` service is registered
  src/DependencyInjection/Compiler/HttpClientTracingPass.php
  tests/DependencyInjection/Compiler/HttpClientTracingPassTest.php
Labels: Type: Bug
