Repository getsentry/sentry-symfony, pull requests merged in 2023-02, with the labels that each got.

#674 Add handled/unhandled exception support
  CHANGELOG.md
  composer.json
  src/EventListener/ConsoleListener.php
  src/EventListener/ErrorListener.php
  src/EventListener/MessengerListener.php
  tests/EventListener/AbstractConsoleListenerTest.php
  tests/EventListener/ErrorListenerTest.php
  tests/EventListener/MessengerListenerTest.php
Labels: Type: Improvement, Status: In Progress

#687 Add a `register_error_handler` config option
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Integration/IntegrationConfigurator.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/error_handler_disabled.php
  tests/DependencyInjection/Fixtures/xml/error_handler_disabled.xml
  tests/DependencyInjection/Fixtures/yml/error_handler_disabled.yml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/Integration/IntegrationConfiguratorTest.php
Labels: Type: Improvement, Status: Backlog

#691 feat: Add before_send_transaction
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
Labels: Type: Feature, Status: In Progress

#692 ref: Use _route as the transaction name
  src/EventListener/TracingRequestListener.php
  tests/EventListener/TracingRequestListenerTest.php
Labels: Type: Improvement, Status: In Progress

#695 Remove php-http/discovery
  composer.json
Labels: Type: Improvement

#690 fix: Sanatize HTTP client spans
  src/Tracing/HttpClient/AbstractTraceableHttpClient.php
  tests/Tracing/HttpClient/TraceableHttpClientTest.php
Labels: Type: Bug, Status: In Progress

#696 Prepare 4.6.0
  CHANGELOG.md
  CONTRIBUTING.md
  composer.json
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/EventListener/ConsoleListener.php
  src/EventListener/ErrorListener.php
  src/EventListener/MessengerListener.php
  src/Integration/IntegrationConfigurator.php
  src/Resources/config/schema/sentry-1.0.xsd
  src/Resources/config/services.xml
  src/Tracing/HttpClient/AbstractTraceableHttpClient.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/Fixtures/php/error_handler_disabled.php
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/error_handler_disabled.xml
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/error_handler_disabled.yml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/EventListener/AbstractConsoleListenerTest.php
  tests/EventListener/ErrorListenerTest.php
  tests/EventListener/MessengerListenerTest.php
  tests/Integration/IntegrationConfiguratorTest.php
  tests/Tracing/HttpClient/TraceableHttpClientTest.php
Labels: Type: Documentation

#697 Switch to MIT license
  LICENSE
  composer.json
Labels: Type: Documentation
