Repository getsentry/sentry-symfony, pull requests merged in 2023-07, with the labels that each got.

#743 Move span tags to span data
  phpstan-baseline.neon
  src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnection.php
  src/Tracing/Doctrine/DBAL/TracingDriverConnectionFactory.php
  src/Tracing/Doctrine/DBAL/TracingStatementForV2.php
  src/Tracing/Doctrine/DBAL/TracingStatementForV3.php
  tests/Tracing/Doctrine/DBAL/TracingDriverConnectionFactoryTest.php
  tests/Tracing/Doctrine/DBAL/TracingDriverConnectionTest.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV2Test.php
  tests/Tracing/Doctrine/DBAL/TracingStatementForV3Test.php
Labels: Type: Improvement, Status: In Progress

#742 Tracing without Performance
  composer.json
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  src/EventListener/TracingRequestListener.php
  src/Resources/config/services.xml
  src/Tracing/HttpClient/AbstractTraceableHttpClient.php
  src/Twig/SentryExtension.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Tracing/HttpClient/TraceableHttpClientTest.php
  tests/Twig/SentryExtensionTest.php
Labels: Type: Feature, Status: In Progress

#748 Set the span status when tracing an HTTP client request
  src/Tracing/HttpClient/AbstractTraceableResponse.php
  tests/Tracing/HttpClient/TraceableHttpClientTest.php
Labels: Type: Improvement

#720 Improve logging of the user when he logged in programmatically
  composer.json
  phpstan-baseline.neon
  src/DependencyInjection/Compiler/AddLoginListenerTagPass.php
  src/EventListener/LoginListener.php
  src/EventListener/RequestListener.php
  src/Resources/config/services.xml
  src/SentryBundle.php
  tests/DependencyInjection/Compiler/AddLoginListenerTagPassTest.php
  tests/EventListener/LoginListenerTest.php
  tests/EventListener/RequestListenerTest.php
Labels: Type: Improvement
