Repository getsentry/sentry-symfony, pull requests merged in 2025-09, with the labels that each got.

#941 fix(logs): use correct option name
  phpstan-baseline.neon
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SentryExtension.php
  src/Resources/config/schema/sentry-1.0.xsd
  tests/DependencyInjection/Fixtures/php/full.php
  tests/DependencyInjection/Fixtures/xml/full.xml
  tests/DependencyInjection/Fixtures/yml/full.yml
  tests/DependencyInjection/SentryExtensionTest.php
  tests/End2End/App/Callback/BeforeSendLogCallback.php
  tests/End2End/App/Controller/LoggingController.php
  tests/End2End/App/logging.yml
  tests/End2End/App/routing.yml
  tests/End2End/LoggingEnd2EndTest.php
Labels: Bug

#949 Prepare 5.4.1
  CHANGELOG.md
Labels: Type: Documentation

#959 fix(logs): Allow passing string and enum Monolog level
  psalm-baseline.xml
  src/Monolog/LogsHandler.php
  tests/Monolog/LogsHandlerTest.php
Labels: Improvement
